dist: trusty
sudo: false

language: generic

matrix:
    include:
        - os: linux
          env: COMPILER=clang++3.7
          addons:
            apt:
                packages: 
                    - clang-3.7
                    - lcov
                    - libblas-dev 
                    - liblapack-dev 
                    - libboost-dev 
                    - libyaml-cpp0.5 
                    - libyaml-cpp-dev 
                sources:
                    - ubuntu-toolchain-r-test

install:
    - mkdir build; 
    - cd build; 
    - cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE:STRING=Debug -DBUILD_Trilinos:BOOL=ON -DCMAKE_INSTALL_PREFIX=$HOME ..;
    - make -j4;

script: ctest

after_success:
  - gem install coveralls-lcov;
  - make coverage;
  - coveralls-lcov coverage.info.cleaned;
